version: '3.8'

services:
  skyform-app:
    build: .
    ports:
      - "9001:9001"
    depends_on:
      - db
    networks:
        - nginx-network

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: skyformDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
        - nginx-network

networks:
  nginx-network:
    external: true